* Your guide to Debian iso downloads

- Current release only: https://cdimage.debian.org/debian-cd/
- Common place for all releases: https://cdimage.debian.org/cdimage/
- Current release in the common place: https://cdimage.debian.org/cdimage/release/

Let's explore the current release location. There you can see a few subdirs. The
ones of interest are =current= (installer) and =current-live= (installer + live
system).

** Live iso

Lets start with =current-live=, it is what most people want. Going into the dir
you'll see there is only one arch to chose from, =amd64=. Descend there.

Now you have a choice: either download from torrents (=bt-hybrid= subdir) or
directly (=iso-hybrid= subdir). Torrents is the better choice, this way you do
not contribute to bandwidth usage on Debian's servers. In case you can't
download from torrents, consider using regional [[https://www.debian.org/CD/http-ftp/#mirrors][mirrors]]. The mirrors host the
same directory structure as outlined above.

Back to the iso images. There are multiple live images which bundle different
desktop environments, one per iso. To say, =debian-live-12.0.0-amd64-gnome.iso=
evidently comes with the GNOME desktop, =debian-live-12.0.0-amd64-kde.iso= has
KDE Plasma and so on. An exception is =debian-live-12.0.0-amd64-standard.iso=
which is text only. So if you pick the GNOME one, you get a live GNOME
environment and installer for Debian with GNOME, 2 in 1. The installer does not
require a network connection.

There is an [[#iso-dvd][alternative]] installer (not a live system) with all desktops included
yet of nearly the same size as those live images. Using it, at some point there
will be a dialog to pick which desktop you'd like. This one does not require a
network connection as well.

** Installer iso

Now we descend into the =current= subdir. There you can see a lot of archs to
choose from. We're only interested in the =amd64= one though, go there.

Here it becomes tricky: there are lots of subdirs with cryptic names. No fear,
it is neat and simple.

*Prefix* meaning:

| bt-    | torrent files for iso images                               |
| iso-   | iso images                                                 |
| jigdo- | template files to reconstruct iso images with =jidgo= tool |
| list-  | list of debs available in corresponding images             |

*Suffix* means size of images based on media capacity:

| -bd   | Blu-ray              |
| -cd   | CD                   |
| -dvd  | DVD                  |
| -dlbd | double layer Blu-ray |
| -16G  | 16G USB stick        |

Points of interest:

*** iso-cd

This is where the =debian-12.0.0-amd64-netinst.iso= netinstaller resides. The
default download link on debian.org points to it. The "net" in the name does not
mean it requires network to do its job. But since it is small (CD size), without
network it can only install the base system. Otherwise there is a dialog to pick
a desktop environment to *download* and install.

*** iso-dvd

Here you can see =debian-12.0.0-amd64-DVD-1.iso=. It is like the netinstaller,
but with all desktops bundled. Using this image you can install Debian with
GNOME, KDE etc on an offline machine.

You can notice this image is marked =DVD-1=. Overall there are 21 =DVD= images
for the current release. You can create the rest with =jigdo= (explained below).

*** iso-bd, iso-dlbd, iso-16G

These either don't contain generic images or don't exist. If you need it, you'd
have to create the images with =jigdo= (explained below). There are five =BD=
images, two =DLBD= and one =16G=.

*** jigdo-X

Here you can see some files with =.jigdo= and =.template= extensions. With that
you can reconstruct all iso images not readily available to download.

The reason behind providing only a few iso images as-is and the rest as jigdo is
most people only need an installer, not the complete set of packages. This way
Debian mirrors don't waste disk space on stuff very rarely used yet still
provide an option to get those extra images.

The first image in a set contains the installer and some debs. The rest only
provide debs. The images can be used as local repositories with help of
=apt-cdrom= tool to reduce network usage or use Debian on an offline system.

Complete sets of =DVD=, =BD= and =DLBD= iso images contain the same set of debs,
namely all Debian packages. The single =16G= image is severely cut down compared
to other variants.

Previously there were also sets of =CD= images. For example in Debian 8.11.0 it
comprised of [[https://cdimage.debian.org/cdimage/archive/8.11.0/amd64/jigdo-cd/][82]] iso images.

Here is how you can build an iso image with jigdo:

- have =jigdo-file= package installed
- run =jigdo-lite= with url to some of the =.jigdo= files
- when asked for Debian mirror to use, make it =http://ftp.debian.org/debian/=

So for example to create all the =BD= images you'd run:

#+begin_src sh
  base=https://cdimage.debian.org/debian-cd/current/amd64/
  for disk in {1..5}; do
      jigdo-lite "$base"/jigdo-bd/debian-12.0.0-amd64-BD-"$disk".jigdo || break
  done
#+end_src

** Mini installer iso

There is also an extremely small installer which requires network to do its
job. The image is named in versionless manner, just =mini.iso=.

The installer is available with [[http://ftp.debian.org/debian/dists/stable/main/installer-amd64/current/images/netboot/][text]] interface and [[http://ftp.debian.org/debian/dists/stable/main/installer-amd64/current/images/netboot/gtk/][GUI]].

** Iso validation example

Debian 12 images are signed with key =6294BE9B=. You can fetch it with such
command:

#+begin_example
  gpg --recv-key --keyserver keyring.debian.org 6294BE9B
#+end_example

With the key acquired and netinstaller downloaded, lets validate it. Go to the
netinstaller's [[https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/][home]] and fetch =SHA256SUMS= and =SHA256SUMS.sign= from there. Put
all three files into the same dir. Next, in that dir we first check the
signature:

#+begin_example
  gpg --verify SHA256SUMS.sign SHA256SUMS
#+end_example

Good response:

#+begin_example
  gpg: Signature made Sat 10 Jun 2023 16:58:34 EEST
  gpg:                using RSA key DF9B9C49EAA9298432589D76DA87E80D6294BE9B
  gpg: Good signature from "Debian CD signing key <debian-cd@lists.debian.org>" [unknown]
  gpg: WARNING: This key is not certified with a trusted signature!
  gpg:          There is no indication that the signature belongs to the owner.
  Primary key fingerprint: DF9B 9C49 EAA9 2984 3258  9D76 DA87 E80D 6294 BE9B
#+end_example

Notice is says "Good signature" and the key used was =6294BE9B=.

Now check the iso:

#+begin_example
  sha256sum -c --ignore-missing SHA256SUMS
#+end_example

Good response:

#+begin_example
  debian-12.0.0-amd64-netinst.iso: OK
#+end_example
